import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ToastContainer} from "react-toastify"
import dbConnect from "../services/mongo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const connect = await dbConnect()
  //console.log(connect); 
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-800">
        {children}
        <ToastContainer />
        </div>
        
      </body>
    </html>
  );
}
